### ISSUE TITLE
TypeError: open_append() missing 1 required positional argument: 'file'

### ISSUE THREAD

**Issue by 1stgongsin** [lieblerj/poi_converter#4]
platform: windows10(x64), python 3.7(x64)

C:\poiconv>python poiconverter.py -if poi -om create bayern.poi bayern.db
Preparing database, please wait ... finished!
Adding POIs ...
**882783** entries [05:40, 2590.78 entries/s]
Finished!
**517970** POIs added to database in 341.46 sec!

What's the difference of the number of entries point and added point ?
I wonder why this happens. Thank you.

**Comment by 1stgongsin** [comment]
-another question

When I command with -om append option, I met error message.

-------------------------------------------------------------------------------------------------------------
(poiconv-ZG7HOUfh) C:\poiconv>python poiconverter.py -if poi -om append bayern2.poi bayern.db
Preparing database, please wait ... Traceback (most recent call last):
  File "poiconverter.py", line 65, in <module>
    main()
  File "poiconverter.py", line 44, in main
    db.open(arguments.output_file, arguments.output_mode)
  File "C:\poiconv\poiconverter\database.py", line 29, in open
    self.open_append()
TypeError: open_append() missing 1 required positional argument: 'file'

**Comment by lieblerj** [comment]
Hi @1stgongsin,

1. The original poi database contains a lot more nodes than are shown in Locus. 
Example: place=hamlet (https://wiki.openstreetmap.org/wiki/Tag:place%3Dhamlet)
or amenity=hunting_stand (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhunting_stand)

poiconverter filters all nodes that are not mentioned in tagfilter.txt. The first number shows the node entries in the original file, the second number shows the number of POIs that were imported into the output file. 

2. Thanks for pointing out the error i will have a look at this.
