### ISSUE TITLE
Usage of poi_converter on a Windows PC

### ISSUE THREAD

**Issue by bmffb** [lieblerj/poi_converter#9]
I would like to use the poi_converter on a Windows PC (Win10, 64bit, python39 installed), but I am running into several issues with obviously needed packages.
- Is it possible to run on a Win PC?
- Is there a detailed installation instruction?
I have build a script to generate mapsforge maps for Locus App on a Windows PC (see: https://www.maiwolf.de/openoutdoormap/index.html). Now I would like to extend it with a Locus compatible poi-db file. 
There are also several issues described in this forum: https://www.openandromaps.org/en/oam-forums/topic/poi-nutzbarkeit-der-dateien-mit-locus/page/7
So I seem not to be the only person having trouble using your code.

By the way, I am from Eichenau by Munich.
Regards
Bernard

**Comment by lieblerj** [comment]
Hi Bernhard,

- it should be possible to run it on a Windows PC 
- i don't have a detailed installation instruction

I also know from the openandromaps.org forum topic that people tried to install it but had problems with the dependencies,  e.g. the spatialite enhanced sqlite library and libosmium. Unfortunately i'm not running Windows so i don't have a system to try it myself.  

You may find some help on the respective project pages:
https://www.gaia-gis.it/fossil/libspatialite/index
https://osmcode.org/pyosmium/

But even there you might get binary releases only for different Linux distributions and MacOS. So i'm not really able to help you with this.

Best regards und Grüsse nach Eichenau,

Jürgen

**Comment by bmffb** [comment]
Hi Jürgen,
thanks for the quick response.
I have tried already to install spatialite and osmium on my Windows PC. No success! With "pip install osmium" I get a long error message without a clear hint what is missing (although they state: "We provide binary wheels for Linux and Windows 64 for all actively maintained Python versions.").
I guess I have to install some Linux or give up. 
Regards,
Bernard
